language: objective-c
osx_image: xcode7.3
cache:
  directories:
  - node_modules
install:
- travis_wait 30 npm install -d --silent
script:
- travis_wait 80 npm run travis
env:
  global:
  - APPNAME="ReactNativeStarterKit"
branches:
  only:
  - master
  - release
  - /^ready\/.+\/.+$/
